alter table BANDMAN_ASSET add constraint FK_BANDMAN_ASSET_INVENTORY_ID foreign key (INVENTORY_ID) references BANDMAN_INVENTORY(ID);
create index IDX_BANDMAN_ASSET_INVENTORY on BANDMAN_ASSET (INVENTORY_ID);
